
name: Test 


on:
  push:
    branches:
      - main
      - master

jobs:
  ansible-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Script
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
          sudo apt update
          sudo apt install ansible
          pip3 install openshift pyyaml kubernetes
          ansible-galaxy collection install kubernetes.core
