name: abc

on: workflow_dispatch
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  my-job:
    runs-on: ubuntu-latest


    steps:
            - name: Import Secrets
              id: import-secrets
              uses: hashicorp/vault-action@v2
              with:
                url: https://hub-vault.apps.tno1-ams.s9nghh76.lab.kubeapp.cloud/
                method: jwt
                path: githubactionsjwt
                role: mustafastakater-nodejssample
                secrets: |
                    stakater/data/github/mustafastakater-nodejssample/secrets abcdefg | ABC ;
            - name: Step following 'Import Secrets'
              run: echo "${{ steps.import-secrets.outputs.ABC }}"
