name: abc

on: workflow_dispatch

jobs:
  my-job:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
            - name: Import Secrets
              id: import-secrets
              uses: hashicorp/vault-action@v2
              with:
                url: https://hub-vault.apps.tno1-ams.s9nghh76.lab.kubeapp.cloud/
                method: jwt
                role: mustafastakater-nodejssample
                jwtGithubAudience: sigstore # set the GitHub token's aud claim

                secrets: |
                    stakater/github/nodejssample abcdefg | ABC ;
            - name: Step following 'Import Secrets'
              run: |
                ABC = "${{ env.ABC }}"
                echo $ABC
